name: Deploy Calendar to GCP VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: SSH Deploy to GCP VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_VM_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

      - name: Clone calcom_calendar on VM
        run: |
          ssh ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
            set -e
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            cd ~
            rm -rf calcom_calendar_fork
            git clone https://${{ secrets.GH_TOKEN }}@github.com/vistaauction/calcom_calendar_fork.git
            cd calcom_calendar_fork
            git submodule update --remote --init
          EOF

      - name: Create and upload .env file
        run: |
          cat > .env <<EOF
          POSTGRES_DB=calcom
          POSTGRES_USER=caluser
          DATABASE_HOST=database:5432
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          DATABASE_URL=postgresql://caluser:${{ secrets.POSTGRES_PASSWORD }}@database:5432/calcom
          DATABASE_DIRECT_URL=postgresql://caluser:${{ secrets.POSTGRES_PASSWORD }}@database:5432/calcom
          NEXT_PUBLIC_WEBAPP_URL=https://${{ secrets.DOMAIN_NAME }}
          NEXT_PUBLIC_API_V2_URL=https://${{ secrets.DOMAIN_NAME }}/api/v2
          NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
          CALENDSO_ENCRYPTION_KEY=${{ secrets.CALENDSO_ENCRYPTION_KEY }}
          NEXT_PUBLIC_SENDGRID_SENDER_NAME=Appointments at Vista Auction
          CALCOM_TELEMETRY_DISABLED=1
          NODE_OPTIONS=--max_old_space_size=16384
          SENDGRID_EMAIL=${{ secrets.SENDGRID_EMAIL }}
          EMAIL_SERVER_HOST=smtp.sendgrid.net
          EMAIL_SERVER_PORT=587
          EMAIL_SERVER_USER=apikey
          EMAIL_SERVER_PASSWORD=${{ secrets.SENDGRID_API_KEY }}
          EMAIL_FROM=${{ secrets.SENDGRID_EMAIL }}
          EMAIL_FROM_NAME=Vista Auction Appointments
          ALLOWED_HOSTNAMES='"vistaapp.tech"'
          NODE_ENV=production
          EOF

          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa .env ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }}:/home/${{ secrets.GCP_VM_USER }}/calcom_calendar_fork/.env

      - name: Run Docker Compose on VM
        run: |
          ssh ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
            set -e
            cd ~/calcom_calendar_fork
            docker compose up -d database
            DOCKER_BUILDKIT=0 docker compose build calcom
            docker compose up -d calcom
          EOF
