name: Deploy Calendar to GCP VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: SSH Deploy to GCP VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_VM_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

      - name: Create .env and copy to VM
        run: |
          echo "POSTGRES_DB=calcom" > .env
          echo "POSTGRES_USER=caluser" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "DATABASE_URL=postgresql://caluser:${{ secrets.POSTGRES_PASSWORD }}@database:5432/calcom" >> .env
          echo "NEXT_PUBLIC_WEBAPP_URL=http://${{ secrets.GCP_VM_IP }}:3000" >> .env
          echo "..." >> .env
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa .env ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }}:/home/${{ secrets.GCP_VM_USER }}/calcom_calendar/.env

      - name: Deploy and build calendar on GCP VM
        run: |
          ssh ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
            set -e

            cd ~
            rm -rf calcom_calendar
            git clone https://github.com/vistaauction/calcom_calendar_fork.git calcom_calendar
            cd calcom_calendar
            git submodule update --remote --init

            docker compose down || true
            docker compose up -d database
            sleep 10

            DOCKER_BUILDKIT=0 docker compose build \
              --build-arg NEXT_PUBLIC_WEBAPP_URL=http://${{ secrets.GCP_VM_IP }}:3000 \
              --build-arg NEXT_PUBLIC_API_V2_URL=http://${{ secrets.GCP_VM_IP }}:3000/api/v2 \
              --build-arg NEXT_PUBLIC_LICENSE_CONSENT=true \
              --build-arg CALCOM_TELEMETRY_DISABLED=1 \
              --build-arg NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
              --build-arg CALENDSO_ENCRYPTION_KEY=${{ secrets.CALENDSO_ENCRYPTION_KEY }} \
              --build-arg DATABASE_URL=postgresql://caluser:${{ secrets.POSTGRES_PASSWORD }}@database:5432/calcom \
              --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              --build-arg MAX_OLD_SPACE_SIZE=16384 \
              calcom

            docker compose up -d calcom
            docker compose ps
          EOF
